# -*- coding: utf-8 -*-
#
# Degeneranki Add-on for Anki
# Copyright (C)  2024 omn0mn0m <https://omn0mn0m.com>
#
# This file was automatically generated by Anki Add-on Builder v1.0.0-dev.5
# It is subject to the same licensing terms as the rest of the program
# (see the LICENSE file which accompanies this program).
#
# WARNING! All changes made in this file will be lost!

"""
Initializes generated Qt forms/resources
"""

__all__ = [
    "degeneranki",
    "inventory"
]

from . import degeneranki
from . import inventory
