# Form implementation generated from reading ui file 'designer/degeneranki.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_degenerankiWidget(object):
    def setupUi(self, degenerankiWidget):
        degenerankiWidget.setObjectName("degenerankiWidget")
        degenerankiWidget.resize(1212, 800)
        self.verticalLayout = QtWidgets.QVBoxLayout(degenerankiWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rollImageLabel = QtWidgets.QLabel(parent=degenerankiWidget)
        self.rollImageLabel.setText("")
        self.rollImageLabel.setPixmap(QtGui.QPixmap("designer/../src/degeneranki/res/wish-background.jpg"))
        self.rollImageLabel.setObjectName("rollImageLabel")
        self.verticalLayout.addWidget(self.rollImageLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rollButton = QtWidgets.QPushButton(parent=degenerankiWidget)
        self.rollButton.setObjectName("rollButton")
        self.horizontalLayout_2.addWidget(self.rollButton)
        self.inventoryButton = QtWidgets.QToolButton(parent=degenerankiWidget)
        self.inventoryButton.setObjectName("inventoryButton")
        self.horizontalLayout_2.addWidget(self.inventoryButton)
        self.settingsButton = QtWidgets.QToolButton(parent=degenerankiWidget)
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout_2.addWidget(self.settingsButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gachaPointsLabel = QtWidgets.QLabel(parent=degenerankiWidget)
        self.gachaPointsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gachaPointsLabel.setObjectName("gachaPointsLabel")
        self.horizontalLayout.addWidget(self.gachaPointsLabel)
        self.pity4StarsLabel = QtWidgets.QLabel(parent=degenerankiWidget)
        self.pity4StarsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pity4StarsLabel.setObjectName("pity4StarsLabel")
        self.horizontalLayout.addWidget(self.pity4StarsLabel)
        self.pity5StarsLabel = QtWidgets.QLabel(parent=degenerankiWidget)
        self.pity5StarsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pity5StarsLabel.setObjectName("pity5StarsLabel")
        self.horizontalLayout.addWidget(self.pity5StarsLabel)
        self.lifetimeRollsLabel = QtWidgets.QLabel(parent=degenerankiWidget)
        self.lifetimeRollsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lifetimeRollsLabel.setObjectName("lifetimeRollsLabel")
        self.horizontalLayout.addWidget(self.lifetimeRollsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(degenerankiWidget)
        QtCore.QMetaObject.connectSlotsByName(degenerankiWidget)

    def retranslateUi(self, degenerankiWidget):
        _translate = QtCore.QCoreApplication.translate
        degenerankiWidget.setWindowTitle(_translate("degenerankiWidget", "Degeneranki"))
        self.rollButton.setText(_translate("degenerankiWidget", "Roll (Cost: 100 Gacha Points)"))
        self.inventoryButton.setText(_translate("degenerankiWidget", "Inventory"))
        self.settingsButton.setText(_translate("degenerankiWidget", "Settings"))
        self.gachaPointsLabel.setText(_translate("degenerankiWidget", "Gacha Points: 0"))
        self.pity4StarsLabel.setText(_translate("degenerankiWidget", "4-Star Pity: 0"))
        self.pity5StarsLabel.setText(_translate("degenerankiWidget", "5-Star Pity: 0"))
        self.lifetimeRollsLabel.setText(_translate("degenerankiWidget", "Lifetime Rolls: 0"))
