# Form implementation generated from reading ui file 'designer/inventory.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(400, 300)
        self.charactersTab = QtWidgets.QWidget()
        self.charactersTab.setObjectName("charactersTab")
        TabWidget.addTab(self.charactersTab, "")
        self.weaponsTab = QtWidgets.QWidget()
        self.weaponsTab.setObjectName("weaponsTab")
        TabWidget.addTab(self.weaponsTab, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "Degeneranki - Inventory"))
        TabWidget.setTabText(TabWidget.indexOf(self.charactersTab), _translate("TabWidget", "Characters"))
        TabWidget.setTabText(TabWidget.indexOf(self.weaponsTab), _translate("TabWidget", "Weapons"))
