[project]
name = 'degeneranki'
version = '0.4.1'

[project.optional-dependencies]
dev = [
    'vendoring==1.2.0',
]

[tool.vendoring]
destination = 'src/degeneranki/vendor/'
requirements = 'src/degeneranki/vendor/vendors.txt'
namespace = 'degeneranki.vendor'
protected-files = [
    '__init__.py',
    'README.md',
    'vendors.txt',
]
patches-dir = 'tools/vendoring/patches'

[tool.vendoring.transformations]
substitute = [
    {match = '__import__("supabase")', replace = '__import__("degeneranki.vendor.supabase")'},
]
drop = [
    'bin/',
    '*.so',
    'typing.*',
    '*/tests/',
]
